version: '3.9'

services:
  kong-gateway:
    build: ./kong
    container_name: kong-gateway

  mssql:
    build: ./mssql
    container_name: mssql

  mongo:
    image: mongo:5.0.5
    container_name: mongo

  postgres:
    build: ./postgres
    container_name: postgres

  redis:
    image: redis:6.2.6-alpine
    container_name: redis

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq

  mailhog:
    image: mailhog/mailhog:1.0.1
    container_name: mailhog

  catalog-service:
    build: ./services/catalog-service
    container_name: catalog-service

  basket-service:
    build: ./services/basket-service
    container_name: basket-service

  review-service:
    build: ./services/review-service
    container_name: review-service

  storage-service:
    build: ./services/storage-service
    container_name: storage-service

  vendor-service:
    build: ./services/vendor-service
    container_name: vendor-service

  payment-service:
    build: ./services/payment-service
    container_name: payment-service

  currency-service:
    build: ./services/currency-service
    container_name: currency-service

  discount-service:
    build: ./services/discount-service
    container_name: discount-service

  coupon-service:
    build: ./services/coupon-service
    container_name: coupon-service

  ordering-service:
    build: ./services/ordering-service
    container_name: ordering-service

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
