version: '3.9'

services:
  kong-gateway:
    build: ./kong
    image: eshop_kong-gateway

  mssql:
    build: ./mssql
    image: eshop_mssql

  mongo:
    image: mongo:5.0.5

  postgres:
    build: ./postgres
    image: eshop_postgres

  redis:
    image: redis:6.2.6-alpine

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine

  mailhog:
    image: mailhog/mailhog:v1.0.1

  catalog-service:
    build: ./services/catalog-service
    image: eshop_catalog-service

  basket-service:
    build: ./services/basket-service
    image: eshop_basket-service

  review-service:
    build: ./services/review-service
    image: eshop_review-service

  storage-service:
    build: ./services/storage-service
    image: eshop_storage-service

  vendor-service:
    build: ./services/vendor-service
    image: eshop_vendor-service

  payment-service:
    build: ./services/payment-service
    image: eshop_payment-service

  currency-service:
    build: ./services/currency-service
    image: eshop_currency-service

  discount-service:
    build: ./services/discount-service
    image: eshop_discount-service

  coupon-service:
    build: ./services/coupon-service
    image: eshop_coupon-service

  ordering-service:
    build: ./services/ordering-service
    image: eshop_ordering-service

  notification-service:
    build: ./services/notification-service
    image: eshop_notification-service

  customer-web-client:
    build: ./clients/customer-web-client
    image: eshop_customer-web-client

  administration-web-client:
    build: ./clients/administration-web-client
    image: eshop_administration-web-client
