version: '3.9'

services:
  kong-gateway:
    build: ./kong

  mssql:
    build: ./mssql

  mongo:
    image: mongo:5.0.5

  postgres:
    build: ./postgres

  redis:
    image: redis:6.2.6-alpine

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine

  mailhog:
    image: mailhog/mailhog:v1.0.1

  catalog-service:
    image: registry.gitlab.com/university-senior-project/catalog-service:1fb79b3d

  review-service:
    image: registry.gitlab.com/university-senior-project/review-service:f5f6d057

  basket-service:
    image: registry.gitlab.com/university-senior-project/basket-service:ced938ff

  storage-service:
    image: registry.gitlab.com/university-senior-project/storage-service:174ebdd4

  vendor-service:
    image: registry.gitlab.com/university-senior-project/vendor-service:9f28847d

  payment-service:
    image: registry.gitlab.com/university-senior-project/payment-service:11ab4d3e

  currency-service:
    image: registry.gitlab.com/university-senior-project/currency-service:6dc4882e

  discount-service:
    image: registry.gitlab.com/university-senior-project/discount-service:d8caca0c

  coupon-service:
    image: registry.gitlab.com/university-senior-project/coupon-service:5e60d246

  ordering-service:
    image: registry.gitlab.com/university-senior-project/ordering-service:0ff88eeb

  notification-service:
    image: registry.gitlab.com/university-senior-project/notification-service:2b2c9676

  # catalog-service:
  #   build: ./services/catalog-service

  # basket-service:
  #   build: ./services/basket-service

  # review-service:
  #   build: ./services/review-service

  # storage-service:
  #   build: ./services/storage-service

  # vendor-service:
  #   build: ./services/vendor-service

  # payment-service:
  #   build: ./services/payment-service

  # currency-service:
  #   build: ./services/currency-service

  # discount-service:
  #   build: ./services/discount-service

  # coupon-service:
  #   build: ./services/coupon-service

  # ordering-service:
  #   build: ./services/ordering-service

  # notification-service:
  #   build: ./services/notification-service

  customer-web-client:
    build: ./clients/customer-web-client

  vendor-web-client:
    build: ./clients/vendor-web-client

  administration-web-client:
    build: ./clients/administration-web-client
